# Total planning attempts
max_solutions: 10

# Planning group and link names
arm_group_name: "arm"
eef_name: "end_effector"
hand_group_name: "gripper"
hand_frame: "j2s6s200_end_effector"
finger_tip_names: ["j2s6s200_link_finger_tip_1","j2s6s200_link_finger_tip_2"]

# Poses
hand_open_pose: "Open"
hand_close_pose: "Close"
arm_home_pose: "Home"

# Scene frames
world_frame: "world"
table_reference_frame: "world"
object_reference_frame: "world"
camera_reference_frame: "world"
surface_link: "table"

# Collision object for picking
# CYLINDER object specifications
spawn_mesh: false
object_name: "object"
object_mesh_file: "package://intrepid_robot_description/meshes/objects/door_handle.dae"
object_dimensions: [0.25, 0.02] # [height, radius]
object_pose: [-0.03, -2, 0.05, 0, 0, 0]

# Camera collision object
spawn_camera: false
camera_name: "camera"
camera_mesh_file: "package://deep_grasp_task/meshes/camera/kinect.dae"
camera_pose: [0.5, 0, 0.7, 0, 0, 0] # side
# camera_pose: [0.5, 0, 0.7, 0, 1.571, 1.571] # over head

# Table model
spawn_table: true
table_name: "table"
table_dimensions: [1, 1, 0.1]  # [length, width, height]
table_pose: [0, -0.7, -0.1, 0, 0, 0]

# Gripper grasp frame transform [x,y,z,r,p,y]
grasp_frame_transform: [0, 0.0, -0.01, 1.5708, 0, 1.5708]

# Place pose [x,y,z,r,p,y]
# place_pose: [-0.03, -2, 0.05, 0, 0, 0]
place_pose: [-0.03, -2, 0.05, 0, 0, 0]
place_surface_offset: 0.0001 # place offset from table

# Valid distance range when approaching an object for picking
approach_object_min_dist: 0.1
approach_object_max_dist: 0.15

# Valid height range when lifting an object after pick
lift_object_min_dist: 0.01
lift_object_max_dist: 0.1
