#holder_table_right:
#  frame_id: table_right_holder_link
#  pose: [[0.0,0.0,-0.01],[0.0,0.0,0.0]] # xyz, rpy
#  geometry:
#    mesh: "package://component_sorting_description/meshes/box/box_holder.stl"

table:
  frame_id: robot_base_footprint
  geometry:
    box:
      length: 1.0
      width: 1.0
      height: 0.1
  pose: [[0.0, -0.7, -0.05],[0.0, 0.0, 0.0]] # xyz, rpy

pick_target:
  frame_id: robot_base_footprint  
  geometry:
    box:
      length: 0.02
      width: 0.02
      height: 0.25
  pose: [[-0.03, -2.0, 0.05],[0.0, 0.0, 0.0]] # xyz, rpy

objects:
  - pick_target