controller_list:
  - name: fake_arm_controller
    type: $(arg execution_type)
    joints:
      - j2s6s200_joint_1
      - j2s6s200_joint_2
      - j2s6s200_joint_3
      - j2s6s200_joint_4
      - j2s6s200_joint_5
      - j2s6s200_joint_6
  - name: fake_gripper_controller
    type: $(arg execution_type)
    joints:
      - j2s6s200_joint_finger_1
      - j2s6s200_joint_finger_2
initial:  # Define initial robot poses.
  - group: arm
    pose: Home
  - group: gripper
    pose: Open